services:
  freqtrade:
    build:
      context: .
      dockerfile: Dockerfile
    image: marklude/milka:latest
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "./user_data:/freqtrade/user_data"
      - "./requirements-freqai.txt:/freqtrade/requirements-freqai.txt"
    ports:
      - "8080:8080"
      - "8081:8081"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy MomentumStrategy
      --freqaimodel BTCPredictionModel
